# Generated by Django 4.2.5 on 2023-09-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_model', models.CharField(max_length=15)),
                ('auto_country', models.CharField(max_length=20)),
                ('auto_year', models.IntegerField()),
                ('auto_number', models.CharField(max_length=10)),
            ],
        ),
    ]
